#Data Preprocessing

In [1]:
import pandas as pd
import numpy as np


In [2]:
data = pd.read_csv('/content/datasets_4458_8204_winequality-red (3).csv')

In [3]:
data

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0               7.4             0.700         0.00  ...       0.56      9.4        5
1               7.8             0.880         0.00  ...       0.68      9.8        5
2               7.8             0.760         0.04  ...       0.65      9.8        5
3              11.2             0.280         0.56  ...       0.58      9.8        6
4               7.4             0.700         0.00  ...       0.56      9.4        5
...             ...               ...          ...  ...        ...      ...      ...
1594            6.2             0.600         0.08  ...       0.58     10.5        5
1595            5.9             0.550         0.10  ...       0.76     11.2        6
1596            6.3             0.510         0.13  ...       0.75     11.0        6
1597            5.9             0.645         0.12  ...       0.71     10.2        5
1598            6.0             0.310         0.47  ...       0.66     11.0        6

[1599 rows x 12 columns]

In [4]:
data['quality'].unique()

array([5, 6, 7, 4, 8, 3])

#Separate Features and Target

* Here lets considering 'quality' as target
*  and rest of the columns as features

In [5]:
x = data.iloc[:,:-1].values
y = data.iloc[:, -1].values

In [6]:
x

array([[ 7.4  ,  0.7  ,  0.   , ...,  3.51 ,  0.56 ,  9.4  ],
       [ 7.8  ,  0.88 ,  0.   , ...,  3.2  ,  0.68 ,  9.8  ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  3.26 ,  0.65 ,  9.8  ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  3.42 ,  0.75 , 11.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  3.57 ,  0.71 , 10.2  ],
       [ 6.   ,  0.31 ,  0.47 , ...,  3.39 ,  0.66 , 11.   ]])

In [7]:
y

array([5, 5, 5, ..., 6, 5, 6])

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [10]:
y_train

array([5, 4, 5, ..., 5, 5, 6])

In [11]:
y_test

array([6, 7, 5, 5, 6, 5, 7, 5, 6, 4, 5, 5, 5, 6, 3, 5, 6, 5, 6, 6, 5, 7,
       5, 5, 6, 5, 5, 7, 7, 6, 6, 6, 7, 5, 5, 6, 5, 5, 4, 6, 6, 6, 6, 5,
       6, 6, 5, 6, 7, 7, 5, 5, 5, 5, 5, 6, 6, 6, 5, 6, 6, 7, 5, 6, 5, 6,
       6, 8, 7, 6, 7, 6, 5, 6, 6, 5, 5, 5, 6, 5, 5, 5, 5, 6, 5, 5, 5, 6,
       6, 8, 6, 5, 6, 4, 5, 5, 6, 6, 5, 5, 5, 6, 5, 6, 6, 6, 5, 7, 7, 6,
       6, 5, 6, 5, 5, 5, 5, 5, 6, 7, 6, 3, 6, 5, 6, 5, 6, 5, 6, 4, 7, 6,
       6, 6, 6, 7, 7, 5, 5, 6, 6, 7, 7, 7, 6, 5, 6, 6, 5, 5, 5, 6, 5, 6,
       6, 6, 4, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 5, 6, 5, 7, 6, 3, 5, 5, 5,
       5, 5, 5, 6, 5, 7, 6, 6, 5, 6, 8, 6, 5, 6, 8, 6, 6, 5, 6, 6, 5, 7,
       7, 5, 6, 6, 7, 6, 5, 5, 6, 5, 5, 6, 5, 7, 5, 6, 5, 6, 5, 7, 5, 5,
       6, 7, 8, 5, 6, 5, 7, 5, 6, 5, 6, 6, 6, 5, 5, 5, 6, 6, 7, 6, 6, 6,
       5, 5, 5, 5, 4, 6, 7, 5, 7, 5, 6, 6, 6, 5, 6, 6, 4, 5, 6, 6, 6, 6,
       5, 6, 6, 8, 6, 5, 5, 6, 5, 6, 7, 6, 6, 4, 6, 5, 5, 6, 5, 4, 6, 6,
       4, 6, 5, 6, 5, 5, 6, 5, 6, 6, 6, 5, 5, 6, 6,

In [12]:
x_train

array([[1.02e+01, 2.40e-01, 4.90e-01, ..., 3.14e+00, 6.10e-01, 1.04e+01],
       [1.25e+01, 4.60e-01, 4.90e-01, ..., 3.05e+00, 5.70e-01, 9.60e+00],
       [7.90e+00, 7.20e-01, 1.00e-02, ..., 3.39e+00, 5.40e-01, 9.60e+00],
       ...,
       [9.60e+00, 5.00e-01, 3.60e-01, ..., 3.18e+00, 6.80e-01, 1.09e+01],
       [7.80e+00, 8.15e-01, 1.00e-02, ..., 3.38e+00, 6.20e-01, 1.08e+01],
       [6.30e+00, 3.60e-01, 1.90e-01, ..., 3.56e+00, 5.20e-01, 1.27e+01]])

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
ntrain = y_train.reshape(len(y_train), 1)
ntest = y_test.reshape(len(y_test), 1)

In [15]:
ntrain

array([[5],
       [4],
       [5],
       ...,
       [5],
       [5],
       [6]])

In [16]:

ntest

array([[6],
       [7],
       [5],
       [5],
       [6],
       [5],
       [7],
       [5],
       [6],
       [4],
       [5],
       [5],
       [5],
       [6],
       [3],
       [5],
       [6],
       [5],
       [6],
       [6],
       [5],
       [7],
       [5],
       [5],
       [6],
       [5],
       [5],
       [7],
       [7],
       [6],
       [6],
       [6],
       [7],
       [5],
       [5],
       [6],
       [5],
       [5],
       [4],
       [6],
       [6],
       [6],
       [6],
       [5],
       [6],
       [6],
       [5],
       [6],
       [7],
       [7],
       [5],
       [5],
       [5],
       [5],
       [5],
       [6],
       [6],
       [6],
       [5],
       [6],
       [6],
       [7],
       [5],
       [6],
       [5],
       [6],
       [6],
       [8],
       [7],
       [6],
       [7],
       [6],
       [5],
       [6],
       [6],
       [5],
       [5],
       [5],
       [6],
       [5],
       [5],
       [5],
       [5],
    

In [17]:
x_sc = StandardScaler()
y_sc = StandardScaler()

In [18]:
xn_train = x_sc.fit_transform(x_train)
yn_train = y_sc.fit_transform(ntrain)

In [19]:
xn_test = x_sc.transform(x_test)
yn_test = y_sc.transform(ntest)

In [20]:
xn_train

array([[ 1.09018218, -1.61183233,  1.13861918, ..., -1.12994532,
        -0.29066856, -0.03185047],
       [ 2.42038622, -0.36861701,  1.13861918, ..., -1.71915486,
        -0.53078811, -0.77646733],
       [-0.24002186,  1.10063746, -1.33325425, ...,  0.50674785,
        -0.71087778, -0.77646733],
       ...,
       [ 0.74317243, -0.14257786,  0.46915346, ..., -0.86807442,
         0.12954065,  0.43353507],
       [-0.29785682,  1.63748044, -1.33325425, ...,  0.44128012,
        -0.23063868,  0.34045796],
       [-1.16538119, -0.93371488, -0.40630171, ...,  1.6196992 ,
        -0.83093755,  2.10892301]])

In [21]:
xn_test

array([[ 1.43719193, -0.70767573,  0.72664027, ..., -1.52275168,
         0.06951076, -1.05569865],
       [-0.47136169, -0.02955829, -0.5607938 , ...,  0.44128012,
        -0.23063868, -0.86954444],
       [ 0.91667731, -0.99022467,  1.44760335, ..., -0.3443326 ,
         0.78986941,  0.15430375],
       ...,
       [ 2.59389109,  1.77875491,  1.85958226, ..., -1.39181623,
        -0.35069845, -0.03185047],
       [ 0.16482285,  1.72224512, -1.38475161, ...,  0.11394149,
        -0.35069845, -0.03185047],
       [ 0.28049276,  0.90285321, -0.04582017, ...,  0.04847376,
        -1.13108699, -0.96262155]])

In [22]:
yn_train

array([[-0.7883837 ],
       [-2.03479006],
       [-0.7883837 ],
       ...,
       [-0.7883837 ],
       [-0.7883837 ],
       [ 0.45802267]])

In [23]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import PolynomialFeatures

In [24]:
r_reg = RandomForestRegressor()
l_reg = LinearRegression()
d_reg = DecisionTreeRegressor()
s_reg = SVR()
p_reg = LinearRegression()

In [25]:
x_pol = PolynomialFeatures(degree=1)
x_pol = x_pol.fit_transform(xn_train)

In [26]:
temp = PolynomialFeatures(degree=1)
temp = temp.fit_transform(xn_test)

In [27]:
r_reg.fit(xn_train, yn_train)
l_reg.fit(xn_train, yn_train)
d_reg.fit(xn_train, yn_train)
s_reg.fit(xn_train, yn_train)
p_reg.fit(x_pol, yn_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [28]:
r_pred = r_reg.predict(xn_test)
l_pred = l_reg.predict(xn_test)
d_pred = d_reg.predict(xn_test)
s_pred = s_reg.predict(xn_test)
p_pred = p_reg.predict(temp)

In [29]:

from sklearn.metrics import r2_score

In [30]:
r = r2_score(yn_test, r_pred)
l = r2_score(yn_test, l_pred)
d = r2_score(yn_test, d_pred)
s = r2_score(yn_test, s_pred)
p = r2_score(yn_test, p_pred)

In [31]:
print(r, l, d, s, p)

0.4578199268738574 0.3176894738338454 0.012797074954296161 0.3595463206018712 0.3176894738338454
